"""
core/itr_parser.py

Parses a filed ITR (Income Tax Return) PDF and extracts the key summary
figures from Part B-TI (Total Income) and Part B-TTI (Tax Liability).

Supports ITR-1, ITR-2, and ITR-3 formats as generated by the Income Tax
Department's e-filing portal.
"""

import re
import logging
from typing import Optional

logger = logging.getLogger(__name__)

try:
    import pdfplumber
    _PDFPLUMBER_AVAILABLE = True
except ImportError:
    _PDFPLUMBER_AVAILABLE = False
    logger.warning("pdfplumber not installed. ITR parsing will not be available.")


def _clean_num(s: str) -> float:
    """Convert a formatted Indian number string (e.g. '1,23,456') to float."""
    if not s:
        return 0.0
    s = s.strip().replace(",", "").replace("(", "-").replace(")", "")
    try:
        return float(s)
    except ValueError:
        return 0.0


def _find_value(text: str, *patterns: str) -> Optional[float]:
    """
    Try multiple regex patterns in order and return the maximum match's value.
    This prevents grabbing intermediate 0s or subtotals instead of the final totals.
    """
    for pattern in patterns:
        matches = re.findall(pattern, text, re.IGNORECASE | re.MULTILINE)
        if matches:
            return max([_clean_num(m) for m in matches])
    return None


def _find_str(text: str, *patterns: str) -> str:
    """Try multiple patterns; return first match group(1) string or ''."""
    for pattern in patterns:
        m = re.search(pattern, text, re.IGNORECASE | re.MULTILINE)
        if m:
            return m.group(1).strip()
    return ""


def parse_itr_pdf(file_bytes: bytes) -> dict:
    """
    Parse a filed ITR PDF and extract detailed summary figures.
    """
    import io

    import tempfile
    import pdfplumber
    import os

    # Monkey-patch pdfplumber.utils.decimalize to prevent crashes on None or PDFColorSpace
    import pdfplumber.utils
    original_decimalize = pdfplumber.utils.decimalize

    def safe_decimalize(v, q=None):
        if v is None:
            return None
        if "PDFColorSpace" in str(type(v)):
            return None
        try:
            return original_decimalize(v, q)
        except Exception:
            return None

    pdfplumber.utils.decimalize = safe_decimalize

    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        tmp.write(file_bytes)
        tmp_path = tmp.name

    try:
        with pdfplumber.open(tmp_path) as pdf:
            pages_text = [page.extract_text() or "" for page in pdf.pages]
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)

    full_text = "\n".join(pages_text)

    # ITR type and AY
    itr_type = _find_str(full_text, r"(ITR[-\s]?[1-6U])", r"Form\s+(ITR-[0-9])")
    if itr_type and not itr_type.upper().startswith("ITR"):
        itr_type = f"ITR-{itr_type}"

    assessment_year = _find_str(full_text, r"Assessment\s+Year[:\s]+(\d{4}-\d{2,4})", r"A\.Y\.[:\s]+(\d{4}-\d{2,4})", r"AY\s+(\d{4}-\d{2})")
    pan = _find_str(full_text, r"PAN\s*[:\-]?\s*([A-Z]{5}[0-9]{4}[A-Z])")
    name = _find_str(full_text, r"Name\s*[:\-]?\s*([A-Z][A-Z\s]{3,60}?)(?:\n|PAN|Date)")

    # Income Heads
    # For ITR-2, final chargeable salary is either in Schedule S line 6 or Part B-TI line 1
    salary = _find_value(
        full_text,
        r"Income chargeable under the Head .Salaries.\s*(?:\([^)]+\))?\s*\d+\s*([\d,]{4,})",
        r"(?:^|\n)\s*1\s+Salaries\s*(?:\([^)]+\))?\s*\d+\s*([\d,]{4,})",
        r"Income chargeable under the head.Salaries.[^\n]*?([\d,]{4,})",
        r"Income from Salary[^\n]*?([\d,]{4,})"
    )
    
    # Gross salary (before Sec 10 exemptions) — from Schedule S line 1 or line 2
    salary_gross = _find_value(
        full_text,
        r"Total gross salary\s*(?:\([^)]+\))?\s*\d+\s*([\d,]{4,})",
        r"Gross Salary\s*(?:\([^)]+\))?\s*\d+\s*([\d,]{4,})",
        r"1\s+Salary[^\n]{0,20}?([\d,]{4,})"
    )
    
    # Salary Exemptions (Sec 10) - from Schedule S line 3 (handle newlines)
    salary_exemptions = _find_value(
        full_text,
        r"Less\s*:\s*Allowances to the extent exempt u/s 10[\s\S]{0,120}?([\d,]{4,})",
        r"Allowances to the extent exempt u/s 10[\s\S]{0,120}?([\d,]{4,})"
    )
    
    house_property = _find_value(full_text, r"(?:Income chargeable under the head 'Income from house property'|Income from House Property).*?([\d,]{3,}|\b0\b)")
    business = _find_value(full_text, r"(?:Profits and gains from business or profession|Income from Business).*?([\d,]{3,}|\b0\b)")
    capital_gains = _find_value(full_text, r"(?:Total Capital Gains|Capital Gains|Income under the head Capital Gains).*?([\d,]{3,}|\b0\b)")
    other_sources = _find_value(full_text, r"(?:Income from other sources).*?([\d,]{3,}|\b0\b)")

    gross_total_income = _find_value(
        full_text,
        r"(?:Gross Total Income).*?([\d,]{3,}|\b0\b)",
        r"Total of all heads.*?([\d,]{3,}|\b0\b)"
    ) or 0.0

    # Deductions
    ded_80c = _find_value(full_text, r"(?:80C\s|80C\n).*?([\d,]{3,}|\b0\b)", r"Life insurance premium.*?([\d,]{3,}|\b0\b)")
    ded_80d = _find_value(full_text, r"(?:80D\s|80D\n).*?([\d,]{3,}|\b0\b)", r"Health insurance premium.*?([\d,]{3,}|\b0\b)")
    ded_80tta_ttb = _find_value(full_text, r"(?:80TTA|80TTB).*?([\d,]{3,}|\b0\b)")
    ded_80ccd1b = _find_value(full_text, r"(?:80CCD\s*\(1B\)).*?([\d,]{3,}|\b0\b)")

    total_deductions = _find_value(
        full_text,
        r"(?:Total Deductions|Deductions under Chapter VI-A).*?([\d,]{3,}|\b0\b)",
        r"Chapter VI-A\s+deductions.*?([\d,]{3,}|\b0\b)"
    ) or 0.0

    # total_taxable_income should be TOTAL INCOME (post-deductions), NOT Gross Total Income.
    # Try to match "Total Income" specifically, falling back to computed GTI - deductions.
    total_taxable_income_raw = _find_value(
        full_text,
        r"(?:^|\n)\s*(?:Total Income|Taxable Total Income)\s+([\d,]{3,})",
        r"(?:Net Income|Total Taxable Income).*?([\d,]{3,}|\b0\b)"
    )
    
    # If the raw value is >= GTI, it's probably reading GTI itself — so compute it correctly
    if total_taxable_income_raw and gross_total_income > 0 and total_taxable_income_raw >= gross_total_income - 100:
        # Derive Total Income from GTI minus deductions
        total_taxable_income = round(gross_total_income - total_deductions, 0)
    elif total_taxable_income_raw:
        total_taxable_income = total_taxable_income_raw
    else:
        total_taxable_income = max(0.0, gross_total_income - total_deductions)

    # Derive total_deductions mathematically if regex failed
    if total_deductions == 0.0 and gross_total_income > 0 and total_taxable_income > 0 and gross_total_income > total_taxable_income:
        total_deductions = round(gross_total_income - total_taxable_income, 0)

    # Tax Liability
    tax_at_slab_rates = _find_value(
        full_text,
        r"(?:Tax at normal rates|Tax at normal slab rates).*?([\d,]{3,}|\b0\b)"
    )
    
    tax_at_special_rate = _find_value(
        full_text,
        r"(?:Tax at special rates|Tax at special rate).*?([\d,]{3,}|\b0\b)"
    )
    
    tax_before_rebate = _find_value(
        full_text,
        r"(?:Tax payable on total income|Tax before rebate).*?([\d,]{3,}|\b0\b)"
    ) or 0.0
    
    # Fallback for tax_on_income if specific fields are not found (for older ITRs or ITR-1)
    tax_on_income = tax_before_rebate
    if not tax_on_income and tax_at_slab_rates is not None:
        tax_on_income = tax_at_slab_rates + (tax_at_special_rate or 0)

    rebate_87a = _find_value(full_text, r"(?:Rebate u/s 87A|Less: Rebate u/s 87A).*?([\d,]{3,}|\b0\b)") or 0.0
    surcharge = _find_value(full_text, r"Surcharge.*?([\d,]{3,}|\b0\b)") or 0.0
    cess = _find_value(full_text, r"(?:Health and Education Cess|Health & Education Cess).*?([\d,]{3,}|\b0\b)") or 0.0

    total_tax_liability = _find_value(
        full_text,
        r"Aggregate liability\s*\(12\+13e\).*?([\d,]{3,}|\b0\b)",
        r"(?:Gross Tax Liability|Net Tax Liability|Total Tax and Cess).*?([\d,]{3,}|\b0\b)"
    ) or 0.0

    # Taxes Paid
    tds_tcs_paid = _find_value(
        full_text, 
        r"TDS\s*\(total of column.*?([\d,]{3,}|\b0\b)",
        r"(?:TDS|Tax Deducted at Source).*?([\d,]{3,}|\b0\b)"
    ) or 0.0
    advance_tax = _find_value(
        full_text, 
        r"Advance Tax\s*\(from column.*?([\d,]{3,}|\b0\b)",
        r"Advance Tax.*?([\d,]{3,}|\b0\b)"
    ) or 0.0
    
    # Check if section 234 or 115 was matched accidentally
    if advance_tax == 234.0: advance_tax = 0.0
    if total_tax_liability == 115.0: total_tax_liability = 0.0

    total_taxes_paid = _find_value(
        full_text,
        r"Total Taxes Paid\s*\(15a.*?([\d,]{3,}|\b0\b)",
        r"Total Taxes Paid.*?([\d,]{3,}|\b0\b)",
        r"Total Tax Paid.*?([\d,]{3,}|\b0\b)"
    ) or (tds_tcs_paid + advance_tax)

    # Refund / Tax Due
    refund = _find_value(full_text, r"Refund.*?([\d,]{3,}|\b0\b)") or 0.0
    tax_due = _find_value(full_text, r"Balance Tax Payable.*?([\d,]{3,}|\b0\b)") or 0.0

    if refund > 0:
        refund_or_tax_due = refund
    elif tax_due > 0:
        refund_or_tax_due = -tax_due
    else:
        refund_or_tax_due = total_taxes_paid - total_tax_liability

    # If total_tax_liability could not be parsed reliably (returned 0 but we have TDS and refund),
    # derive it mathematically: total_tax = tds_paid + advance_tax - refund
    if total_tax_liability == 0.0 and (tds_tcs_paid > 0 or advance_tax > 0) and refund > 0:
        total_tax_liability = round(tds_tcs_paid + advance_tax - refund, 2)

    # If rebate_87a was missed by regex but we have the other components, derive it mathematically:
    # Tax Liability = (Tax Before Rebate - Rebate + Surcharge) + Cess
    # Therefore: Rebate = Tax Before Rebate + Surcharge + Cess - Tax Liability
    if rebate_87a == 0.0 and tax_before_rebate > 0 and total_tax_liability > 0:
        derived_rebate = round(tax_before_rebate + surcharge + cess - total_tax_liability, 0)
        if derived_rebate > 0:
            rebate_87a = derived_rebate

    return {
        "itr_type": itr_type or "Unknown",
        "assessment_year": assessment_year or "2025-26",
        "pan": pan,
        "name": name,
        
        "income": {
            "salary": salary,
            "salary_gross": salary_gross,
            "salary_exemptions": salary_exemptions,
            "house_property": house_property,
            "business": business,
            "capital_gains": capital_gains,
            "other_sources": other_sources,
            "gross_total": gross_total_income
        },
        "deductions": {
            "sec_80c": ded_80c,
            "sec_80d": ded_80d,
            "sec_80tta_ttb": ded_80tta_ttb,
            "sec_80ccd1b": ded_80ccd1b,
            "total": total_deductions
        },
        "tax": {
            "taxable_income": total_taxable_income,
            "tax_on_income": tax_on_income, # Keeps backward compatibility
            "tax_at_slab_rates": tax_at_slab_rates,
            "tax_at_special_rate": tax_at_special_rate,
            "tax_before_rebate": tax_before_rebate,
            "rebate_87a": rebate_87a,
            "surcharge": surcharge,
            "cess": cess,
            "total_tax_liability": total_tax_liability,
            "tds_paid": tds_tcs_paid,
            "advance_tax": advance_tax,
            "total_taxes_paid": total_taxes_paid,
            "refund_or_due": refund_or_tax_due
        }
    }
